name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Destination Repository
      - name: Checkout Destination Repository
        uses: actions/checkout@v3
        with:
          path: destination

      # Step 2: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: suchali93/miguel-portfolio
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          path: source

      # Step 3: Install Dependencies
      - name: Install Dependencies
        working-directory: source
        run: npm ci

      # Step 4: Build Project
      - name: Build Project
        working-directory: source
        run: npm run build

      # Step 5: Copy Build Output
      - name: Copy Build Output
        run: |
          rm -rf destination/*
          cp -r source/build/* destination/

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        working-directory: destination
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy updates from miguel-portfolio" || echo "No changes to commit"
          git push origin main
